location = /index.html {
    expires -1;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}

location = /service-worker.js {
    expires -1;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}

location = /sw.js {
    try_files /service-worker.js =404;
    expires -1;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}

location = /manifest.json {
    expires -1;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}

location = /manifest-ios.json {
    expires -1;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}
